- name: Copying Mongo Repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb-Org
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Enable and Start Mongodb-Org
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Allow remote
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart Mongodb-Org
  ansible.builtin.service:
    name: mongod
    state: restarted
