- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop

- name: remove app directory recursively
  ansible.builtin.file:
    path: /app
    state: absent

- name: Add App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download required code
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /tmp/catalogue.zip

- name: Unzip Catalogue Zip
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes
