- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop

- name: remove app directory recursively
  ansible.builtin.file:
    path: /app
    state: absent

- name: Add App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} app"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: "/tmp/{{component}}.zip"

- name: "Unzip {{component}} Zip"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes
