- name: Copying Mongo Repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb shell
  ansible.builtin.package:
    name: mongodb-org-shell

- name: get the entries count
  ansible.builtin.command: mongo --host mongo.jagadishdaws.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: entries_count
  when: component == "catalogue"

- name: get the entries count

  ansible.builtin.command: mongo --host mongodb.jagadishdaws.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: entries_count
  when: component == "user"

- name: load {{component}} data

  ansible.builtin.command: "mongo --host mongodb.jagadishdaws.online < /app/schema/{{component}}.js"
  when: product_count.stdout == "0"
