- name: Copying catalogie service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: starting catalogue
  ansible.builtin.systemd_service:
    name: catalogue
    daemon_reload: true

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes
