- name: "Copying {{component}} service file"
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: "/etc/systemd/system/{{component}}.service"

- name: starting catalogue
  ansible.builtin.systemd_service:
    name: catalogue
    daemon_reload: true

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes
